package com.cdc.ccmx.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;


public class ResponseTaxReturn {
  @SerializedName("@id")
  private String id1 = null;
  @SerializedName("@type")
  private String type1 = "TaxReturn";
  @SerializedName("id")
  private UUID id = null;
  @SerializedName("taxpayer")
  private ResponseTaxpayer taxpayer = null;
  @SerializedName("operationNumber")
  private Double operationNumber = null;
  @SerializedName("intervalUnit")
  private String intervalUnit = null;
  @SerializedName("period")
  private String period = null;
  @SerializedName("fiscalYear")
  private String fiscalYear = null;
  @SerializedName("type")
  private String type = null;
  @SerializedName("complementary")
  private ResponseCredentialType complementary = null;
  @SerializedName("presentedAt")
  private String presentedAt = null;
  @SerializedName("captureLine")
  private String captureLine = null;
  @SerializedName("files")
  private List<ResponseFile> files = null;
  @SerializedName("payment")
  private ResponseCredentialType payment = null;
  @SerializedName("createdAt")
  private String createdAt = null;
  @SerializedName("updatedAt")
  private String updatedAt = null;
   
  @ApiModelProperty(example = "/tax-returns/91106968-1abd-4d64-85c1-4e73d96fb997", value = "Tax return IRI reference")
  public String getId1() {
    return id1;
  }
   
  @ApiModelProperty(value = "")
  public String getType1() {
    return type1;
  }
   
  @ApiModelProperty(example = "91106968-1abd-4d64-85c1-4e73d96fb997", value = "Tax Return ID")
  public UUID getId() {
    return id;
  }
  public ResponseTaxReturn taxpayer(ResponseTaxpayer taxpayer) {
    this.taxpayer = taxpayer;
    return this;
  }
   
  @ApiModelProperty(value = "")
  public ResponseTaxpayer getTaxpayer() {
    return taxpayer;
  }
  public void setTaxpayer(ResponseTaxpayer taxpayer) {
    this.taxpayer = taxpayer;
  }
   
  @ApiModelProperty(example = "2.00100172932E11", value = "Tax return operation code generated by SAT (Número de operación)")
  public Double getOperationNumber() {
    return operationNumber;
  }
  public ResponseTaxReturn intervalUnit(String intervalUnit) {
    this.intervalUnit = intervalUnit;
    return this;
  }
   
  @ApiModelProperty(value = "")
  public String getIntervalUnit() {
    return intervalUnit;
  }
  public void setIntervalUnit(String intervalUnit) {
    this.intervalUnit = intervalUnit;
  }
  public ResponseTaxReturn period(String period) {
    this.period = period;
    return this;
  }
   
  @ApiModelProperty(example = "Diciembre", value = "Fiscal period. For an annual tax return, it is a year and for monthly tax return it is a month")
  public String getPeriod() {
    return period;
  }
  public void setPeriod(String period) {
    this.period = period;
  }
   
  @ApiModelProperty(example = "2019", value = "Fiscal year")
  public String getFiscalYear() {
    return fiscalYear;
  }
  public ResponseTaxReturn type(String type) {
    this.type = type;
    return this;
  }
   
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }
  public ResponseTaxReturn complementary(ResponseCredentialType complementary) {
    this.complementary = complementary;
    return this;
  }
   
  @ApiModelProperty(value = "")
  public ResponseCredentialType getComplementary() {
    return complementary;
  }
  public void setComplementary(ResponseCredentialType complementary) {
    this.complementary = complementary;
  }
  public ResponseTaxReturn presentedAt(String presentedAt) {
    this.presentedAt = presentedAt;
    return this;
  }
   
  @ApiModelProperty(value = "Tax return filing date")
  public String getPresentedAt() {
    return presentedAt;
  }
  public void setPresentedAt(String presentedAt) {
    this.presentedAt = presentedAt;
  }
  public ResponseTaxReturn captureLine(String captureLine) {
    this.captureLine = captureLine;
    return this;
  }
   
  @ApiModelProperty(example = "042007HZ795527888246", value = "Set when the an amount should be paid back to SAT")
  public String getCaptureLine() {
    return captureLine;
  }
  public void setCaptureLine(String captureLine) {
    this.captureLine = captureLine;
  }
  public ResponseTaxReturn files(List<ResponseFile> files) {
    this.files = files;
    return this;
  }
  public ResponseTaxReturn addFilesItem(ResponseFile filesItem) {
    if (this.files == null) {
      this.files = new ArrayList<ResponseFile>();
    }
    this.files.add(filesItem);
    return this;
  }
   
  @ApiModelProperty(value = "Tax return PDF files (ack receipt, transcript and payment receipt)")
  public List<ResponseFile> getFiles() {
    return files;
  }
  public void setFiles(List<ResponseFile> files) {
    this.files = files;
  }
  public ResponseTaxReturn payment(ResponseCredentialType payment) {
    this.payment = payment;
    return this;
  }
   
  @ApiModelProperty(value = "")
  public ResponseCredentialType getPayment() {
    return payment;
  }
  public void setPayment(ResponseCredentialType payment) {
    this.payment = payment;
  }
   
  @ApiModelProperty(example = "2020-01-01T12:15:00.000Z", value = "Date and time the resource was created")
  public String getCreatedAt() {
    return createdAt;
  }
   
  @ApiModelProperty(example = "2020-01-01T12:15:00.000Z", value = "Date and time the resource was last updated")
  public String getUpdatedAt() {
    return updatedAt;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseTaxReturn responseTaxReturn = (ResponseTaxReturn) o;
    return Objects.equals(this.id, responseTaxReturn.id) &&
        Objects.equals(this.type, responseTaxReturn.type) &&
        Objects.equals(this.id, responseTaxReturn.id) &&
        Objects.equals(this.taxpayer, responseTaxReturn.taxpayer) &&
        Objects.equals(this.operationNumber, responseTaxReturn.operationNumber) &&
        Objects.equals(this.intervalUnit, responseTaxReturn.intervalUnit) &&
        Objects.equals(this.period, responseTaxReturn.period) &&
        Objects.equals(this.fiscalYear, responseTaxReturn.fiscalYear) &&
        Objects.equals(this.type, responseTaxReturn.type) &&
        Objects.equals(this.complementary, responseTaxReturn.complementary) &&
        Objects.equals(this.presentedAt, responseTaxReturn.presentedAt) &&
        Objects.equals(this.captureLine, responseTaxReturn.captureLine) &&
        Objects.equals(this.files, responseTaxReturn.files) &&
        Objects.equals(this.payment, responseTaxReturn.payment) &&
        Objects.equals(this.createdAt, responseTaxReturn.createdAt) &&
        Objects.equals(this.updatedAt, responseTaxReturn.updatedAt);
  }
  @Override
  public int hashCode() {
    return Objects.hash(id, type, id, taxpayer, operationNumber, intervalUnit, period, fiscalYear, type, complementary, presentedAt, captureLine, files, payment, createdAt, updatedAt);
  }
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseTaxReturn {\n");
    
    sb.append("    id: ").append(toIndentedString(id1)).append("\n");
    sb.append("    type: ").append(toIndentedString(type1)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    taxpayer: ").append(toIndentedString(taxpayer)).append("\n");
    sb.append("    operationNumber: ").append(toIndentedString(operationNumber)).append("\n");
    sb.append("    intervalUnit: ").append(toIndentedString(intervalUnit)).append("\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("    fiscalYear: ").append(toIndentedString(fiscalYear)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    complementary: ").append(toIndentedString(complementary)).append("\n");
    sb.append("    presentedAt: ").append(toIndentedString(presentedAt)).append("\n");
    sb.append("    captureLine: ").append(toIndentedString(captureLine)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("    payment: ").append(toIndentedString(payment)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }
  
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
