package com.cdc.ccmx.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;


public class ResponseTaxComplianceCheck {
  @SerializedName("@id")
  private String id1 = null;
  @SerializedName("@type")
  private String type = "TaxComplianceCheck";
  @SerializedName("id")
  private String id = null;
  @SerializedName("file")
  private ResponseFile file = null;
  @SerializedName("internalIdentifier")
  private String internalIdentifier = null;
  @SerializedName("taxpayer")
  private ResponseTaxComplianceTaxpayer taxpayer = null;
  @SerializedName("result")
  private String result = null;
  @SerializedName("checkedAt")
  private String checkedAt = null;
  @SerializedName("createdAt")
  private String createdAt = null;
   
  @ApiModelProperty(example = "/tax-compliance-checks/91106968-1abd-4d64-85c1-4e73d96fb997", value = "Tax compliance check IRI reference")
  public String getId1() {
    return id1;
  }
   
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }
  public ResponseTaxComplianceCheck id(String id) {
    this.id = id;
    return this;
  }
   
  @ApiModelProperty(example = "91106968-1abd-4d64-85c1-4e73d96fb997", value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }
  public ResponseTaxComplianceCheck file(ResponseFile file) {
    this.file = file;
    return this;
  }
   
  @ApiModelProperty(value = "")
  public ResponseFile getFile() {
    return file;
  }
  public void setFile(ResponseFile file) {
    this.file = file;
  }
  public ResponseTaxComplianceCheck internalIdentifier(String internalIdentifier) {
    this.internalIdentifier = internalIdentifier;
    return this;
  }
   
  @ApiModelProperty(example = "20NE1234567", value = "The internal identifier (folio) generated by the SAT")
  public String getInternalIdentifier() {
    return internalIdentifier;
  }
  public void setInternalIdentifier(String internalIdentifier) {
    this.internalIdentifier = internalIdentifier;
  }
  public ResponseTaxComplianceCheck taxpayer(ResponseTaxComplianceTaxpayer taxpayer) {
    this.taxpayer = taxpayer;
    return this;
  }
   
  @ApiModelProperty(value = "")
  public ResponseTaxComplianceTaxpayer getTaxpayer() {
    return taxpayer;
  }
  public void setTaxpayer(ResponseTaxComplianceTaxpayer taxpayer) {
    this.taxpayer = taxpayer;
  }
  public ResponseTaxComplianceCheck result(String result) {
    this.result = result;
    return this;
  }
   
  @ApiModelProperty(value = "")
  public String getResult() {
    return result;
  }
  public void setResult(String result) {
    this.result = result;
  }
   
  @ApiModelProperty(example = "2020-01-01T12:15:00.000Z", value = "Check date")
  public String getCheckedAt() {
    return checkedAt;
  }
   
  @ApiModelProperty(example = "2020-01-01T12:15:00.000Z", value = "Date and time the resource was created")
  public String getCreatedAt() {
    return createdAt;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseTaxComplianceCheck responseTaxComplianceCheck = (ResponseTaxComplianceCheck) o;
    return Objects.equals(this.id, responseTaxComplianceCheck.id) &&
        Objects.equals(this.type, responseTaxComplianceCheck.type) &&
        Objects.equals(this.id, responseTaxComplianceCheck.id) &&
        Objects.equals(this.file, responseTaxComplianceCheck.file) &&
        Objects.equals(this.internalIdentifier, responseTaxComplianceCheck.internalIdentifier) &&
        Objects.equals(this.taxpayer, responseTaxComplianceCheck.taxpayer) &&
        Objects.equals(this.result, responseTaxComplianceCheck.result) &&
        Objects.equals(this.checkedAt, responseTaxComplianceCheck.checkedAt) &&
        Objects.equals(this.createdAt, responseTaxComplianceCheck.createdAt);
  }
  @Override
  public int hashCode() {
    return Objects.hash(id, type, id, file, internalIdentifier, taxpayer, result, checkedAt, createdAt);
  }
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseTaxComplianceCheck {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("    internalIdentifier: ").append(toIndentedString(internalIdentifier)).append("\n");
    sb.append("    taxpayer: ").append(toIndentedString(taxpayer)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    checkedAt: ").append(toIndentedString(checkedAt)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }
  
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
